-- CreateTable
CREATE TABLE `Transaction` (
    `id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `type` ENUM('DEPOSIT', 'EXPENSE', 'INVESTIMENT') NOT NULL,
    `amount` DECIMAL(10, 2) NOT NULL,
    `category` ENUM('EDUCATION', 'ENTERTAINMENT', 'FOOD', 'HEALTH', 'HOUSING', 'OTHER', 'SALARY', 'TRANSPORTATION', 'UTILITY') NOT NULL,
    `paymentMethod` ENUM('BANK_SLIP', 'BANK_TRANSFER', 'CASH', 'CREDIT_CARD', 'DEBIT_CARD', 'OTHER', 'PIX') NOT NULL,
    `date` DATETIME(3) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
